"""Add is_admin column to User table

Revision ID: 26522175cd7b
Revises: 70d580c95e81
Create Date: 2025-04-15 22:33:58.124924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26522175cd7b'
down_revision = '70d580c95e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['per_id'])
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['per_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_id', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['per_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('per_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_1', 'user', ['author_id'], ['id'])
        batch_op.drop_column('per_id')

    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('per_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_2', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('comment_ibfk_1', 'user', ['author_id'], ['id'])
        batch_op.drop_column('per_id')

    # ### end Alembic commands ###
